### ISSUE TITLE
Bill of materials

### ISSUE THREAD

**Issue by foorschtbar** [NPoole/KeychainTapeCounter#1]
Very cool gadget you have developed. I liked it since i saw it on twitter. 

Will you upload a BOM so that everybody can build the BeanCounter yourself - or did I just overlook that?

**Comment by e-tinkers** [comment]
Well, for those who know electronics and embedded programming, one could create a device like this and write his own code even without seeing the schematic. 

For those who can't even generate the BOM (or who is capable but unwilling to invest time on it) when giving the component footprints, PCB layout and schematic, maybe one should just buy one from the @Npoole and support his [CrownSupply](https://www.crowdsupply.com/great-big-factory/beancounter) project.

**Comment by foorschtbar** [comment]
I have not seen that the Eagle files are there. Now everything is clear.
